name: Semgrep & Auto PR Approve

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    # Random HH:MM to avoid GitHub load spikes
    - cron: '35 11 * * *'

jobs:
  semgrep:
    name: Semgrep CI Scan
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]'
    container:
      image: returntocorp/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: semgrep ci

  auto-approve:
    name: Auto-Approve Logo PRs
    runs-on: ubuntu-latest
    needs: semgrep
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    steps:
      - name: Auto-Approve if Logo Detected
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
